server:
  port: 80

spring:
  application:
    name: 代码生成器-开发环境
  mvc:
    view:
      suffix: .jsp
  freemarker:
    request-context-attribute: req
    suffix: .ftl
    content-type: text/html; charset=UTF-8
    enabled: true
    cache: false
    template-loader-path: classpath:/templates/
    charset: UTF-8
    settings:
      number_format: '0.##'
      auto_import: spring.ftl as spring
      default_encoding: UTF-8
      output_encoding: UTF-8
      template_exception_handler: com.chqiuu.cgp.handler.FreemarkerExceptionHandler

logging:
  file:
    name: logs\code_log.log

generator:
  map-query-enabled: false
  lombok-data-enabled: true
  swagger-enable: true