server:
  port: 803

spring:
  application:
    name: 代码生成器-开发环境
  mvc:
    view:
      suffix: .jsp
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  freemarker:
    #req访问request
    request-context-attribute: req
    #后缀名
    suffix: .ftl
    content-type: text/html; charset=UTF-8
    enabled: true
    #缓存配置
    cache: false
    #模板加载路径 按需配置
    template-loader-path: classpath:templates/, file:./templates/
    charset: UTF-8 #编码格式
    expose-spring-macro-helpers: true
    settings:
      #数字格式化，无小数点
      number_format: '0.##'
      auto_import: spring.ftl as spring
      default_encoding: UTF-8
      output_encoding: UTF-8
      template_exception_handler: com.chqiuu.cgp.handler.FreemarkerExceptionHandler

generator:
  map-query-enabled: false
  lombok-data-enabled: true
  swagger-enable: true